In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv("../data/raw/application_train.csv")
previous_df=pd.read_csv("../data/raw/previous_application.csv")

In [3]:
print("Shape:", df.shape)
print("shape2:", previous_df.shape)

Shape: (307511, 122)
shape2: (1670214, 37)

In [4]:
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.022,0.0198,0.0,0.0,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.00,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,26.0,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.008019,-19005,-3039,-9833.0,-2437,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.650442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,2.0,0.0,-617.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.028663,-19932,-3038,-4311.0,-3458,NaN,1,1,0,1,0,0,Core staff,1.0,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.322738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1106.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
previous_df.head()

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,Y,1,0.0,0.182832,0.867336,XAP,Approved,-73,Cash through the bank,XAP,NaN,Repeater,Mobile,POS,XNA,Country-wide,35,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,Y,1,NaN,NaN,NaN,XNA,Approved,-164,XNA,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,Contact center,-1,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,Y,1,NaN,NaN,NaN,XNA,Approved,-301,Cash through the bank,XAP,"Spouse, partner",Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,Y,1,NaN,NaN,NaN,XNA,Approved,-512,Cash through the bank,XAP,NaN,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,Y,1,NaN,NaN,NaN,Repairs,Refused,-781,Cash through the bank,HC,NaN,Repeater,XNA,Cash,walk-in,Credit and cash offices,-1,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:

print("\nDuplicate rows:", df.duplicated().sum())

print("\nData types:")
print(df.dtypes.value_counts())

Duplicate rows: 0

Data types:
float64    65
int64      41
str        16
Name: count, dtype: int64

In [7]:
float_columns = df.select_dtypes(include=['float64']).columns
int_columns = df.select_dtypes(include=['int64']).columns
str_columns = df.select_dtypes(include=['object']).columns

C:\Users\mitali\AppData\Local\Temp\ipykernel_17372\883509169.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  str_columns = df.select_dtypes(include=['object']).columns

In [8]:
# Float columns null percentage
float_null_percentage = (df[float_columns].isnull().mean() * 100).round(2)
float_null_percentage = float_null_percentage[float_null_percentage > 0].sort_values(ascending=False)

print("FLOAT COLUMNS NULL %:")
print(float_null_percentage)

FLOAT COLUMNS NULL %:
COMMONAREA_AVG                  69.87
COMMONAREA_MODE                 69.87
COMMONAREA_MEDI                 69.87
NONLIVINGAPARTMENTS_AVG         69.43
NONLIVINGAPARTMENTS_MODE        69.43
NONLIVINGAPARTMENTS_MEDI        69.43
LIVINGAPARTMENTS_MODE           68.35
LIVINGAPARTMENTS_AVG            68.35
LIVINGAPARTMENTS_MEDI           68.35
FLOORSMIN_AVG                   67.85
FLOORSMIN_MODE                  67.85
FLOORSMIN_MEDI                  67.85
YEARS_BUILD_MEDI                66.50
YEARS_BUILD_MODE                66.50
YEARS_BUILD_AVG                 66.50
OWN_CAR_AGE                     65.99
LANDAREA_MEDI                   59.38
LANDAREA_MODE                   59.38
LANDAREA_AVG                    59.38
BASEMENTAREA_MEDI               58.52
BASEMENTAREA_MODE               58.52
BASEMENTAREA_AVG                58.52
EXT_SOURCE_1                    56.38
NONLIVINGAREA_MODE              55.18
NONLIVINGAREA_AVG               55.18
NONLIVINGAREA_MEDI              55.18
ELEVATORS_MODE                  53.30
ELEVATORS_MEDI                  53.30
ELEVATORS_AVG                   53.30
APARTMENTS_AVG                  50.75
APARTMENTS_MEDI                 50.75
APARTMENTS_MODE                 50.75
ENTRANCES_AVG                   50.35
ENTRANCES_MODE                  50.35
ENTRANCES_MEDI                  50.35
LIVINGAREA_MEDI                 50.19
LIVINGAREA_AVG                  50.19
LIVINGAREA_MODE                 50.19
FLOORSMAX_MODE                  49.76
FLOORSMAX_AVG                   49.76
FLOORSMAX_MEDI                  49.76
YEARS_BEGINEXPLUATATION_AVG     48.78
YEARS_BEGINEXPLUATATION_MEDI    48.78
YEARS_BEGINEXPLUATATION_MODE    48.78
TOTALAREA_MODE                  48.27
EXT_SOURCE_3                    19.83
AMT_REQ_CREDIT_BUREAU_QRT       13.50
AMT_REQ_CREDIT_BUREAU_YEAR      13.50
AMT_REQ_CREDIT_BUREAU_HOUR      13.50
AMT_REQ_CREDIT_BUREAU_DAY       13.50
AMT_REQ_CREDIT_BUREAU_MON       13.50
AMT_REQ_CREDIT_BUREAU_WEEK      13.50
DEF_30_CNT_SOCIAL_CIRCLE         0.33
OBS_30_CNT_SOCIAL_CIRCLE         0.33
OBS_60_CNT_SOCIAL_CIRCLE         0.33
DEF_60_CNT_SOCIAL_CIRCLE         0.33
EXT_SOURCE_2                     0.21
AMT_GOODS_PRICE                  0.09
dtype: float64

In [9]:
# Integer columns null percentage
int_null_percentage = (df[int_columns].isnull().mean() * 100).round(2)
int_null_percentage = int_null_percentage[int_null_percentage > 0].sort_values(ascending=False)

print("\nINTEGER COLUMNS NULL %:")
print(int_null_percentage)

INTEGER COLUMNS NULL %:
Series([], dtype: float64)

In [10]:
str_null_percentage = (df[str_columns].isnull().mean() * 100).round(2)
str_null_percentage = str_null_percentage[str_null_percentage > 0].sort_values(ascending=False)

print("\nSTRING COLUMNS NULL %:")
print(str_null_percentage)

STRING COLUMNS NULL %:
FONDKAPREMONT_MODE     68.39
WALLSMATERIAL_MODE     50.84
HOUSETYPE_MODE         50.18
EMERGENCYSTATE_MODE    47.40
OCCUPATION_TYPE        31.35
NAME_TYPE_SUITE         0.42
dtype: float64

In [11]:
for col in df.select_dtypes(include=["object", "string"]).columns:
    print(f"\nColumn: {col}")
    print(
        df[col]
        .value_counts(normalize=True)
        .mul(100)
        .round(2)
        .to_string()
    )

Column: NAME_CONTRACT_TYPE
NAME_CONTRACT_TYPE
Cash loans         90.48
Revolving loans     9.52

Column: CODE_GENDER
CODE_GENDER
F      65.83
M      34.16
XNA     0.00

Column: FLAG_OWN_CAR
FLAG_OWN_CAR
N    65.99
Y    34.01

Column: FLAG_OWN_REALTY
FLAG_OWN_REALTY
Y    69.37
N    30.63

Column: NAME_TYPE_SUITE
NAME_TYPE_SUITE
Unaccompanied      81.16
Family             13.11
Spouse, partner     3.71
Children            1.07
Other_B             0.58
Other_A             0.28
Group of people     0.09

Column: NAME_INCOME_TYPE
NAME_INCOME_TYPE
Working                 51.63
Commercial associate    23.29
Pensioner               18.00
State servant            7.06
Unemployed               0.01
Student                  0.01
Businessman              0.00
Maternity leave          0.00

Column: NAME_EDUCATION_TYPE
NAME_EDUCATION_TYPE
Secondary / secondary special    71.02
Higher education                 24.34
Incomplete higher                 3.34
Lower secondary                   1.24
Academic degree                   0.05

Column: NAME_FAMILY_STATUS
NAME_FAMILY_STATUS
Married                 63.88
Single / not married    14.78
Civil marriage           9.68
Separated                6.43
Widow                    5.23
Unknown                  0.00

Column: NAME_HOUSING_TYPE
NAME_HOUSING_TYPE
House / apartment      88.73
With parents            4.83
Municipal apartment     3.64
Rented apartment        1.59
Office apartment        0.85
Co-op apartment         0.36

Column: OCCUPATION_TYPE
OCCUPATION_TYPE
Laborers                 26.14
Sales staff              15.21
Core staff               13.06
Managers                 10.12
Drivers                   8.81
High skill tech staff     5.39
Accountants               4.65
Medicine staff            4.04
Security staff            3.18
Cooking staff             2.82
Cleaning staff            2.20
Private service staff     1.26
Low-skill Laborers        0.99
Waiters/barmen staff      0.64
Secretaries               0.62
Realty agents             0.36
HR staff                  0.27
IT staff                  0.25

Column: WEEKDAY_APPR_PROCESS_START
WEEKDAY_APPR_PROCESS_START
TUESDAY      17.53
WEDNESDAY    16.89
MONDAY       16.49
THURSDAY     16.45
FRIDAY       16.37
SATURDAY     11.01
SUNDAY        5.26

Column: ORGANIZATION_TYPE
ORGANIZATION_TYPE
Business Entity Type 3    22.11
XNA                       18.01
Self-employed             12.49
Other                      5.43
Medicine                   3.64
Business Entity Type 2     3.43
Government                 3.38
School                     2.89
Trade: type 7              2.55
Kindergarten               2.24
Construction               2.19
Business Entity Type 1     1.95
Transport: type 4          1.76
Trade: type 3              1.14
Industry: type 9           1.10
Industry: type 3           1.07
Security                   1.06
Housing                    0.96
Industry: type 11          0.88
Military                   0.86
Bank                       0.82
Agriculture                0.80
Police                     0.76
Transport: type 2          0.72
Postal                     0.70
Security Ministries        0.64
Trade: type 2              0.62
Restaurant                 0.59
Services                   0.51
University                 0.43
Industry: type 7           0.43
Transport: type 3          0.39
Industry: type 1           0.34
Hotel                      0.31
Electricity                0.31
Industry: type 4           0.29
Trade: type 6              0.21
Industry: type 5           0.19
Insurance                  0.19
Telecom                    0.19
Emergency                  0.18
Industry: type 2           0.15
Advertising                0.14
Realtor                    0.13
Culture                    0.12
Industry: type 12          0.12
Trade: type 1              0.11
Mobile                     0.10
Legal Services             0.10
Cleaning                   0.08
Transport: type 1          0.07
Industry: type 6           0.04
Industry: type 10          0.04
Religion                   0.03
Industry: type 13          0.02
Trade: type 4              0.02
Trade: type 5              0.02
Industry: type 8           0.01

Column: FONDKAPREMONT_MODE
FONDKAPREMONT_MODE
reg oper account         75.94
reg oper spec account    12.43
not specified             5.85
org spec account          5.78

Column: HOUSETYPE_MODE
HOUSETYPE_MODE
block of flats      98.23
specific housing     0.98
terraced house       0.79

Column: WALLSMATERIAL_MODE
WALLSMATERIAL_MODE
Panel           43.69
Stone, brick    42.88
Block            6.12
Wooden           3.55
Mixed            1.52
Monolithic       1.18
Others           1.07

Column: EMERGENCYSTATE_MODE
EMERGENCYSTATE_MODE
No     98.56
Yes     1.44

In [12]:
for col in [
    'WALLSMATERIAL_MODE',
    'HOUSETYPE_MODE',
    'EMERGENCYSTATE_MODE',
    'OCCUPATION_TYPE',
    'FONDKAPREMONT_MODE'
]:
    df[col] = df[col].fillna('Unknown')


df['NAME_TYPE_SUITE'] = df['NAME_TYPE_SUITE'].fillna(
    df['NAME_TYPE_SUITE'].mode()[0]
)

In [13]:
building_groups = {
    'COMMONAREA': ['COMMONAREA_AVG', 'COMMONAREA_MODE', 'COMMONAREA_MEDI'],
    'NONLIVINGAPARTMENTS': [
        'NONLIVINGAPARTMENTS_AVG',
        'NONLIVINGAPARTMENTS_MODE',
        'NONLIVINGAPARTMENTS_MEDI'
    ],
    'LIVINGAPARTMENTS': [
        'LIVINGAPARTMENTS_AVG',
        'LIVINGAPARTMENTS_MODE',
        'LIVINGAPARTMENTS_MEDI'
    ],
    'FLOORSMIN': ['FLOORSMIN_AVG', 'FLOORSMIN_MODE', 'FLOORSMIN_MEDI'],
    'YEARS_BUILD': ['YEARS_BUILD_AVG', 'YEARS_BUILD_MODE', 'YEARS_BUILD_MEDI']
}

for name, cols in building_groups.items():
    print(f"\n{name}")
    print(df[cols].corr())

COMMONAREA
                 COMMONAREA_AVG  COMMONAREA_MODE  COMMONAREA_MEDI
COMMONAREA_AVG         1.000000         0.977147         0.995978
COMMONAREA_MODE        0.977147         1.000000         0.979887
COMMONAREA_MEDI        0.995978         0.979887         1.000000

NONLIVINGAPARTMENTS
                          NONLIVINGAPARTMENTS_AVG  NONLIVINGAPARTMENTS_MODE  \
NONLIVINGAPARTMENTS_AVG                  1.000000                  0.969370
NONLIVINGAPARTMENTS_MODE                 0.969370                  1.000000
NONLIVINGAPARTMENTS_MEDI                 0.990768                  0.978575

                          NONLIVINGAPARTMENTS_MEDI
NONLIVINGAPARTMENTS_AVG                   0.990768
NONLIVINGAPARTMENTS_MODE                  0.978575
NONLIVINGAPARTMENTS_MEDI                  1.000000

LIVINGAPARTMENTS
                       LIVINGAPARTMENTS_AVG  LIVINGAPARTMENTS_MODE  \
LIVINGAPARTMENTS_AVG               1.000000               0.970117
LIVINGAPARTMENTS_MODE              0.970117               1.000000
LIVINGAPARTMENTS_MEDI              0.993825               0.975605

                       LIVINGAPARTMENTS_MEDI
LIVINGAPARTMENTS_AVG                0.993825
LIVINGAPARTMENTS_MODE               0.975605
LIVINGAPARTMENTS_MEDI               1.000000

FLOORSMIN
                FLOORSMIN_AVG  FLOORSMIN_MODE  FLOORSMIN_MEDI
FLOORSMIN_AVG        1.000000        0.985875        0.997241
FLOORSMIN_MODE       0.985875        1.000000        0.988406
FLOORSMIN_MEDI       0.997241        0.988406        1.000000

YEARS_BUILD
                  YEARS_BUILD_AVG  YEARS_BUILD_MODE  YEARS_BUILD_MEDI
YEARS_BUILD_AVG          1.000000          0.989444          0.998495
YEARS_BUILD_MODE         0.989444          1.000000          0.989463
YEARS_BUILD_MEDI         0.998495          0.989463          1.000000

In [14]:
cols_drop = [
    'COMMONAREA_MODE', 'COMMONAREA_MEDI',
    
    'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAPARTMENTS_MEDI',
    
    'LIVINGAPARTMENTS_MODE', 'LIVINGAPARTMENTS_MEDI',
    
    'FLOORSMIN_MODE', 'FLOORSMIN_MEDI',
    
    'YEARS_BUILD_MODE', 'YEARS_BUILD_MEDI'
]

df.drop(columns=cols_drop, inplace=True)

In [15]:
building_groups = {
    'LANDAREA': ['LANDAREA_AVG', 'LANDAREA_MODE', 'LANDAREA_MEDI'],
    'BASEMENTAREA': ['BASEMENTAREA_AVG', 'BASEMENTAREA_MODE', 'BASEMENTAREA_MEDI'],
    'NONLIVINGAREA': ['NONLIVINGAREA_AVG', 'NONLIVINGAREA_MODE', 'NONLIVINGAREA_MEDI'],
    'ELEVATORS': ['ELEVATORS_AVG', 'ELEVATORS_MODE', 'ELEVATORS_MEDI'],
    'APARTMENTS': ['APARTMENTS_AVG', 'APARTMENTS_MODE', 'APARTMENTS_MEDI'],
    'ENTRANCES': ['ENTRANCES_AVG', 'ENTRANCES_MODE', 'ENTRANCES_MEDI'],
    'LIVINGAREA': ['LIVINGAREA_AVG', 'LIVINGAREA_MODE', 'LIVINGAREA_MEDI'],
    'FLOORSMAX': ['FLOORSMAX_AVG', 'FLOORSMAX_MODE', 'FLOORSMAX_MEDI'],
    'YEARS_BEGINEXPLUATATION': [
        'YEARS_BEGINEXPLUATATION_AVG',
        'YEARS_BEGINEXPLUATATION_MODE',
        'YEARS_BEGINEXPLUATATION_MEDI'
    ]
}

for name, cols in building_groups.items():
    print(f"\n{name}")
    print(df[cols].corr())

LANDAREA
               LANDAREA_AVG  LANDAREA_MODE  LANDAREA_MEDI
LANDAREA_AVG       1.000000       0.973696       0.991610
LANDAREA_MODE      0.973696       1.000000       0.980835
LANDAREA_MEDI      0.991610       0.980835       1.000000

BASEMENTAREA
                   BASEMENTAREA_AVG  BASEMENTAREA_MODE  BASEMENTAREA_MEDI
BASEMENTAREA_AVG           1.000000           0.973496           0.994317
BASEMENTAREA_MODE          0.973496           1.000000           0.977938
BASEMENTAREA_MEDI          0.994317           0.977938           1.000000

NONLIVINGAREA
                    NONLIVINGAREA_AVG  NONLIVINGAREA_MODE  NONLIVINGAREA_MEDI
NONLIVINGAREA_AVG            1.000000            0.966087            0.990444
NONLIVINGAREA_MODE           0.966087            1.000000            0.975839
NONLIVINGAREA_MEDI           0.990444            0.975839            1.000000

ELEVATORS
                ELEVATORS_AVG  ELEVATORS_MODE  ELEVATORS_MEDI
ELEVATORS_AVG        1.000000        0.978837        0.996099
ELEVATORS_MODE       0.978837        1.000000        0.982828
ELEVATORS_MEDI       0.996099        0.982828        1.000000

APARTMENTS
                 APARTMENTS_AVG  APARTMENTS_MODE  APARTMENTS_MEDI
APARTMENTS_AVG         1.000000         0.973259         0.995081
APARTMENTS_MODE        0.973259         1.000000         0.977193
APARTMENTS_MEDI        0.995081         0.977193         1.000000

ENTRANCES
                ENTRANCES_AVG  ENTRANCES_MODE  ENTRANCES_MEDI
ENTRANCES_AVG        1.000000        0.977743        0.996886
ENTRANCES_MODE       0.977743        1.000000        0.980677
ENTRANCES_MEDI       0.996886        0.980677        1.000000

LIVINGAREA
                 LIVINGAREA_AVG  LIVINGAREA_MODE  LIVINGAREA_MEDI
LIVINGAREA_AVG         1.000000         0.972050         0.995596
LIVINGAREA_MODE        0.972050         1.000000         0.974743
LIVINGAREA_MEDI        0.995596         0.974743         1.000000

FLOORSMAX
                FLOORSMAX_AVG  FLOORSMAX_MODE  FLOORSMAX_MEDI
FLOORSMAX_AVG        1.000000        0.985689        0.997034
FLOORSMAX_MODE       0.985689        1.000000        0.988237
FLOORSMAX_MEDI       0.997034        0.988237        1.000000

YEARS_BEGINEXPLUATATION
                              YEARS_BEGINEXPLUATATION_AVG  \
YEARS_BEGINEXPLUATATION_AVG                      1.000000
YEARS_BEGINEXPLUATATION_MODE                     0.971893
YEARS_BEGINEXPLUATATION_MEDI                     0.993825

                              YEARS_BEGINEXPLUATATION_MODE  \
YEARS_BEGINEXPLUATATION_AVG                       0.971893
YEARS_BEGINEXPLUATATION_MODE                      1.000000
YEARS_BEGINEXPLUATATION_MEDI                      0.963539

                              YEARS_BEGINEXPLUATATION_MEDI
YEARS_BEGINEXPLUATATION_AVG                       0.993825
YEARS_BEGINEXPLUATATION_MODE                      0.963539
YEARS_BEGINEXPLUATATION_MEDI                      1.000000

In [16]:

cols_to_drop = [
    # LANDAREA
    'LANDAREA_MODE', 'LANDAREA_MEDI',

    # BASEMENTAREA
    'BASEMENTAREA_MODE', 'BASEMENTAREA_MEDI',

    # NONLIVINGAREA
    'NONLIVINGAREA_MODE', 'NONLIVINGAREA_MEDI',

    # ELEVATORS
    'ELEVATORS_MODE', 'ELEVATORS_MEDI',

    # APARTMENTS
    'APARTMENTS_MODE', 'APARTMENTS_MEDI',

    # ENTRANCES
    'ENTRANCES_MODE', 'ENTRANCES_MEDI',

    # LIVINGAREA
    'LIVINGAREA_MODE', 'LIVINGAREA_MEDI',

    # FLOORSMAX
    'FLOORSMAX_MODE', 'FLOORSMAX_MEDI',

    # YEARS_BEGINEXPLUATATION
    'YEARS_BEGINEXPLUATATION_MODE',
    'YEARS_BEGINEXPLUATATION_MEDI'
]

df.drop(columns=cols_to_drop, inplace=True)

In [17]:
df.shape

(307511, 94)

In [18]:
null_percentage = (df.isnull().sum() / len(df)) * 100

null_percentage = null_percentage[null_percentage > 0].sort_values(ascending=False)

print(null_percentage)

COMMONAREA_AVG                 69.872297
NONLIVINGAPARTMENTS_AVG        69.432963
LIVINGAPARTMENTS_AVG           68.354953
FLOORSMIN_AVG                  67.848630
YEARS_BUILD_AVG                66.497784
OWN_CAR_AGE                    65.990810
LANDAREA_AVG                   59.376738
BASEMENTAREA_AVG               58.515956
EXT_SOURCE_1                   56.381073
NONLIVINGAREA_AVG              55.179164
ELEVATORS_AVG                  53.295980
APARTMENTS_AVG                 50.749729
ENTRANCES_AVG                  50.348768
LIVINGAREA_AVG                 50.193326
FLOORSMAX_AVG                  49.760822
YEARS_BEGINEXPLUATATION_AVG    48.781019
TOTALAREA_MODE                 48.268517
EXT_SOURCE_3                   19.825307
AMT_REQ_CREDIT_BUREAU_QRT      13.501631
AMT_REQ_CREDIT_BUREAU_WEEK     13.501631
AMT_REQ_CREDIT_BUREAU_YEAR     13.501631
AMT_REQ_CREDIT_BUREAU_HOUR     13.501631
AMT_REQ_CREDIT_BUREAU_MON      13.501631
AMT_REQ_CREDIT_BUREAU_DAY      13.501631
OBS_60_CNT_SOCIAL_CIRCLE        0.332021
DEF_60_CNT_SOCIAL_CIRCLE        0.332021
DEF_30_CNT_SOCIAL_CIRCLE        0.332021
OBS_30_CNT_SOCIAL_CIRCLE        0.332021
EXT_SOURCE_2                    0.214626
AMT_GOODS_PRICE                 0.090403
AMT_ANNUITY                     0.003902
CNT_FAM_MEMBERS                 0.000650
DAYS_LAST_PHONE_CHANGE          0.000325
dtype: float64

In [19]:
df['TARGET'].isnull().sum()

np.int64(0)

In [20]:
df['COMMONAREA_AVG'] = df.groupby(
    'REGION_RATING_CLIENT'
)['COMMONAREA_AVG'].transform(
    lambda x: x.fillna(x.median())
)

In [21]:
null_percentage = (df.isnull().sum() / len(df)) * 100

null_percentage = null_percentage[null_percentage > 0].sort_values(ascending=False)

print(null_percentage)

NONLIVINGAPARTMENTS_AVG        69.432963
LIVINGAPARTMENTS_AVG           68.354953
FLOORSMIN_AVG                  67.848630
YEARS_BUILD_AVG                66.497784
OWN_CAR_AGE                    65.990810
LANDAREA_AVG                   59.376738
BASEMENTAREA_AVG               58.515956
EXT_SOURCE_1                   56.381073
NONLIVINGAREA_AVG              55.179164
ELEVATORS_AVG                  53.295980
APARTMENTS_AVG                 50.749729
ENTRANCES_AVG                  50.348768
LIVINGAREA_AVG                 50.193326
FLOORSMAX_AVG                  49.760822
YEARS_BEGINEXPLUATATION_AVG    48.781019
TOTALAREA_MODE                 48.268517
EXT_SOURCE_3                   19.825307
AMT_REQ_CREDIT_BUREAU_YEAR     13.501631
AMT_REQ_CREDIT_BUREAU_WEEK     13.501631
AMT_REQ_CREDIT_BUREAU_DAY      13.501631
AMT_REQ_CREDIT_BUREAU_QRT      13.501631
AMT_REQ_CREDIT_BUREAU_MON      13.501631
AMT_REQ_CREDIT_BUREAU_HOUR     13.501631
OBS_30_CNT_SOCIAL_CIRCLE        0.332021
OBS_60_CNT_SOCIAL_CIRCLE        0.332021
DEF_30_CNT_SOCIAL_CIRCLE        0.332021
DEF_60_CNT_SOCIAL_CIRCLE        0.332021
EXT_SOURCE_2                    0.214626
AMT_GOODS_PRICE                 0.090403
AMT_ANNUITY                     0.003902
CNT_FAM_MEMBERS                 0.000650
DAYS_LAST_PHONE_CHANGE          0.000325
dtype: float64

In [22]:
prev_null_percentage = (
    previous_df.isnull().mean() * 100
).sort_values(ascending=False)

print(prev_null_percentage[prev_null_percentage > 0])

RATE_INTEREST_PRIVILEGED     99.643698
RATE_INTEREST_PRIMARY        99.643698
AMT_DOWN_PAYMENT             53.636480
RATE_DOWN_PAYMENT            53.636480
NAME_TYPE_SUITE              49.119754
DAYS_TERMINATION             40.298129
DAYS_FIRST_DRAWING           40.298129
DAYS_FIRST_DUE               40.298129
DAYS_LAST_DUE_1ST_VERSION    40.298129
DAYS_LAST_DUE                40.298129
NFLAG_INSURED_ON_APPROVAL    40.298129
AMT_GOODS_PRICE              23.081773
AMT_ANNUITY                  22.286665
CNT_PAYMENT                  22.286366
PRODUCT_COMBINATION           0.020716
AMT_CREDIT                    0.000060
dtype: float64

In [23]:
previous_df.drop(
    columns=[
        'RATE_INTEREST_PRIVILEGED',
        'RATE_INTEREST_PRIMARY'
    ],
    inplace=True
)

In [24]:
previous_df['NAME_TYPE_SUITE'] = (
    previous_df['NAME_TYPE_SUITE'].fillna('Unknown')
)

In [25]:
prev_fe = previous_df.copy()

In [26]:
prev_features = (
    prev_fe.groupby('SK_ID_CURR')
    .agg(
        PREV_APP_COUNT=('SK_ID_PREV', 'count')
    )
    .reset_index()
)

In [27]:
numeric_features = (
    prev_fe.groupby('SK_ID_CURR')
    .agg(
        PREV_AMT_APPLICATION_MEAN=('AMT_APPLICATION', 'mean'),
        PREV_AMT_APPLICATION_MAX=('AMT_APPLICATION', 'max'),

        PREV_AMT_CREDIT_MEAN=('AMT_CREDIT', 'mean'),
        PREV_AMT_CREDIT_MAX=('AMT_CREDIT', 'max'),

        PREV_AMT_ANNUITY_MEAN=('AMT_ANNUITY', 'mean'),
        PREV_AMT_GOODS_PRICE_MEAN=('AMT_GOODS_PRICE', 'mean'),

        PREV_CNT_PAYMENT_MEAN=('CNT_PAYMENT', 'mean'),

        PREV_AMT_DOWN_PAYMENT_MEAN=('AMT_DOWN_PAYMENT', 'mean'),
        PREV_RATE_DOWN_PAYMENT_MEAN=('RATE_DOWN_PAYMENT', 'mean')
    )
    .reset_index()
)

In [28]:
prev_features = prev_features.merge(
    numeric_features,
    on='SK_ID_CURR',
    how='left'
)

In [29]:
status_features = (
    pd.crosstab(
        prev_fe['SK_ID_CURR'],
        prev_fe['NAME_CONTRACT_STATUS']
    )
    .reset_index()
)

In [30]:
status_features.columns = [
    'SK_ID_CURR'
] + [
    f'PREV_STATUS_{col.upper().replace(" ", "_")}'
    for col in status_features.columns[1:]
]

In [31]:
prev_features = prev_features.merge(
    status_features,
    on='SK_ID_CURR',
    how='left'
)

In [32]:
if 'PREV_STATUS_APPROVED' in prev_features.columns:
    prev_features['PREV_APPROVAL_RATE'] = (
        prev_features['PREV_STATUS_APPROVED']
        / prev_features['PREV_APP_COUNT']
    )

In [33]:
if 'PREV_STATUS_REFUSED' in prev_features.columns:
    prev_features['PREV_REFUSAL_RATE'] = (
        prev_features['PREV_STATUS_REFUSED']
        / prev_features['PREV_APP_COUNT']
    )

In [34]:
print(prev_features.shape)
print(prev_features['SK_ID_CURR'].duplicated().sum())

(338857, 17)
0

In [35]:
df = df.merge(
    prev_features,
    on='SK_ID_CURR',
    how='left'
)

In [36]:
print(df.shape)

(307511, 110)

In [37]:
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,PREV_APP_COUNT,PREV_AMT_APPLICATION_MEAN,PREV_AMT_APPLICATION_MAX,PREV_AMT_CREDIT_MEAN,PREV_AMT_CREDIT_MAX,PREV_AMT_ANNUITY_MEAN,PREV_AMT_GOODS_PRICE_MEAN,PREV_CNT_PAYMENT_MEAN,PREV_AMT_DOWN_PAYMENT_MEAN,PREV_RATE_DOWN_PAYMENT_MEAN,PREV_STATUS_APPROVED,PREV_STATUS_CANCELED,PREV_STATUS_REFUSED,PREV_STATUS_UNUSED_OFFER,PREV_APPROVAL_RATE,PREV_REFUSAL_RATE
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,179055.00,179055.0,179055.00,179055.0,9251.775,179055.00,24.000000,0.00,0.000000,1.0,0.0,0.0,0.0,1.000000,0.000000
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,435436.50,900000.0,484191.00,1035882.0,56553.990,435436.50,10.000000,3442.50,0.050030,3.0,0.0,0.0,0.0,1.000000,0.000000
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,26.0,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,0.0198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,Unknown,NaN,Unknown,Unknown,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,24282.00,24282.0,20106.00,20106.0,5357.250,24282.00,4.000000,4860.00,0.212008,1.0,0.0,0.0,0.0,1.000000,0.000000
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.008019,-19005,-3039,-9833.0,-2437,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.650442,NaN,NaN,NaN,NaN,NaN,0.0198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,Unknown,NaN,Unknown,Unknown,2.0,0.0,2.0,0.0,-617.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,9.0,272203.26,688500.0,291695.50,906615.0,23651.175,408304.89,23.000000,34840.17,0.163412,5.0,3.0,1.0,0.0,0.555556,0.111111
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.028663,-19932,-3038,-4311.0,-3458,NaN,1,1,0,1,0,0,Core staff,1.0,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.322738,NaN,NaN,NaN,NaN,NaN,0.0198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,Unknown,NaN,Unknown,Unknown,0.0,0.0,0.0,0.0,-1106.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,150530.25,247500.0,166638.75,284400.0,12278.805,150530.25,20.666667,3390.75,0.159516,6.0,0.0,0.0,0.0,1.000000,0.000000

In [38]:
df.describe()

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,PREV_APP_COUNT,PREV_AMT_APPLICATION_MEAN,PREV_AMT_APPLICATION_MAX,PREV_AMT_CREDIT_MEAN,PREV_AMT_CREDIT_MAX,PREV_AMT_ANNUITY_MEAN,PREV_AMT_GOODS_PRICE_MEAN,PREV_CNT_PAYMENT_MEAN,PREV_AMT_DOWN_PAYMENT_MEAN,PREV_RATE_DOWN_PAYMENT_MEAN,PREV_STATUS_APPROVED,PREV_STATUS_CANCELED,PREV_STATUS_REFUSED,PREV_STATUS_UNUSED_OFFER,PREV_APPROVAL_RATE,PREV_REFUSAL_RATE
count,307511.000000,307511.000000,307511.000000,3.075110e+05,3.075110e+05,307499.000000,3.072330e+05,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,104582.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307509.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,134133.000000,3.068510e+05,246546.000000,151450.00000,127568.000000,157504.000000,103023.000000,307511.000000,143620.000000,152683.000000,154491.000000,98869.000000,124921.000000,97312.000000,153161.000000,93997.000000,137829.000000,159080.000000,306490.000000,306490.000000,306490.000000,306490.000000,307510.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.00000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,265992.000000,265992.000000,265992.000000,265992.000000,265992.000000,265992.000000,291057.000000,2.910570e+05,2.910570e+05,2.910570e+05,2.910570e+05,290640.000000,2.900820e+05,290642.000000,2.736050e+05,273605.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000
mean,278180.518577,0.080729,0.417052,1.687979e+05,5.990260e+05,27108.573909,5.383962e+05,0.020868,-16036.995067,63815.045904,-4986.120328,-2994.202373,12.061091,0.999997,0.819889,0.199368,0.998133,0.281066,0.056720,2.152665,2.052463,2.031521,12.063419,0.015144,0.050769,0.040659,0.078173,0.230454,0.179555,0.502130,5.143927e-01,0.510853,0.11744,0.088442,0.977735,0.752471,0.027824,0.078942,0.149725,0.226282,0.231894,0.066333,0.100775,0.107399,0.008809,0.028358,0.102547,1.422245,0.143421,1.405292,0.100049,-962.858788,0.000042,0.710023,0.000081,0.015115,0.088055,0.000192,0.081376,0.003896,0.000023,0.003912,0.000007,0.003525,0.002936,0.00121,0.009928,0.000267,0.008130,0.000595,0.000507,0.000335,0.006402,0.007000,0.034362,0.267395,0.265474,1.899974,4.857128,1.540055e+05,3.745905e+05,1.700700e+05,4.138656e+05,14532.052781,1.938959e+05,14.530822,7.080503e+03,0.081924,3.044417,0.891375,0.843099,0.078236,0.748855,0.110902
std,102790.175348,0.272419,0.722121,2.371231e+05,4.024908e+05,14493.737315,3.694465e+05,0.013831,4363.988632,141275.766519,3522.886321,1509.450419,11.944812,0.001803,0.384280,0.399526,0.043164,0.449521,0.231307,0.910682,0.509034,0.502737,3.265832,0.122126,0.219526,0.197499,0.268444,0.421124,0.383817,0.211062,1.910602e-01,0.194844,0.10824,0.082438,0.059223,0.113280,0.043226,0.134576,0.100049,0.144641,0.161380,0.081184,0.092576,0.110565,0.047732,0.069523,0.107462,2.400989,0.446698,2.379803,0.362291,826.808487,0.006502,0.453752,0.009016,0.122010,0.283376,0.013850,0.273412,0.062295,0.004771,0.062424,0.002550,0.059268,0.054110,0.03476,0.099144,0.016327,0.089798,0.024387,0.022518,0.018299,0.083849,0.110757,0.204685,0.916002,0.794056,1.869295,4.147042,1.532878e+05,4.219951e+05,1.657372e+05,4.575384e+05,10007.483472,1.925761e+05,8.419878,1.842180e+04,0.089517,2.124588,1.675430,1.813868,0.326501,0.262332,0.184348
min,100002.000000,0.000000,0.000000,2.565000e+04,4.500000e+04,1615.500000,4.050000e+04,0.000290,-25229.000000,-17912.000000,-24672.000000,-7197.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.014568,8.173617e-08,0.000527,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4292.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,-2.250000e-01,-0.000007,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,189145.500000,0.000000,0.000000,1.125000e+05,2.700000e+05,16524.000000,2.385000e+05,0.010006,-19682.000000,-2760.000000,-7479.500000,-4299.000000,5.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,2.000000,2.000000,2.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.334007,3.924574e-01,0.370650,0.05770,0.044200,0.976700,0.687200,0.019800,0.000000,0.069000,0.166700,0.083300,0.018700,0.050400,0.045300,0.000000,0.000000,0.041200,0.000000,0.000000,0.000000,0.000000,-1570.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,6.192574e+04,9.831150e+04,6.684943e+04,1.044315e+05,7835.967188,7.355700e+04,9.000000,0.000000e+00,0.000000,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000
50%,278202.000000,0.000000,0.000000,1.471500e+05,5.135310e+05,24903.000000,4.500000e+05,0.018850,-15750.000000,-1213.000000,-4504.000000,-3254.000000,9.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,2.000000,2.000000,2.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.505998,5.659614e-01,0.535276,0.08760,0.076300,0.981600,0.755200,0.019800,0.000000,0.137900,0.166700,0.208300,0.048100,0.075600,0.074500,0.000000,0.003600,0.068800,0.000000,0.000000,0.000000,0.000000,-757.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,1.060020e+05,2.025000e+05,1.174500e+05,2.250000e+05,11984.355000,1.285912e+05,12.000000,3.375000e+03,0.066315,3.000000,0.000000,0.000000,0.000000,0.800000,0.000000
75%,367142.500000,0.000000,1.000000,2.025000e+05,8.086500e+05,34596.000000,6.795000e+05,0.028663,-12413.000000,-289.000000,-2010.000000,-1720.000000,15.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,3.000000,2.000000,2.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.675053,6.636171e-01,0.669057,0.14850,0.112200,0.986600,0.823200,0.019800,0.120000,0.206900,0.333300,0.375000,0.085600,0.121000,0.129900,0.003900,0.027700,0.127600,2.000000,0.000000,2.000000,0.000000,-274.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,6.000000,1.912500e+05,4.545000e+05,2.160720e+05,5.473440e+05,18330.313500,2.449018e+05,18.000000,8.282250e+03,0.108914,4.000000,1.000000,1.000000,0.000000,1.000000,0.200000
max,456255.000000,1.000000,19.000000,1.170000e+08,4.050000e+06,258025.500000,4.050000e+06,0.072508,-7489.000000,365243.000000,0.000000,0.000000,91.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,20.000000,3.000000,3.000000,23.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.962693,8.549997e-01,0.896010,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,348.000000,34.000000,344.000000,24.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,9.000000,8.000000,27.000000,261.000000,25.000000,73.000000,4.050000e+06,5.850000e+06,4.050000e+06,4.509688e+06,300425.445000,4.050000e+06,72.000000,2.025000e+06,0.989740,27.000000,58.000000,68.000000,16.000000,1.000000,1.000000

In [39]:
df['PREV_APP_COUNT'].isnull().sum()

np.int64(16454)

In [40]:
df['PREV_APP_COUNT'] = df['PREV_APP_COUNT'].fillna(0)

In [41]:
count_cols = [
    'PREV_STATUS_APPROVED',
    'PREV_STATUS_CANCELED',
    'PREV_STATUS_REFUSED',
    'PREV_STATUS_UNUSED_OFFER'
]

df[count_cols] = df[count_cols].fillna(0)

In [42]:
mean_cols = [
    'PREV_AMT_APPLICATION_MEAN',
    'PREV_AMT_APPLICATION_MAX',
    'PREV_AMT_CREDIT_MEAN',
    'PREV_AMT_CREDIT_MAX',
    'PREV_AMT_ANNUITY_MEAN',
    'PREV_AMT_GOODS_PRICE_MEAN',
    'PREV_CNT_PAYMENT_MEAN',
    'PREV_AMT_DOWN_PAYMENT_MEAN',
    'PREV_RATE_DOWN_PAYMENT_MEAN'
]

In [43]:
rate_cols = [
    'PREV_APPROVAL_RATE',
    'PREV_REFUSAL_RATE'
]

df[rate_cols] = df[rate_cols].fillna(0)

In [44]:
# 1. Create indicator before filling nulls
df['HAS_PREV_APPLICATION'] = (
    df['PREV_APP_COUNT'].notna()
).astype(int)


# 2. No previous applications = 0 applications
df['PREV_APP_COUNT'] = df['PREV_APP_COUNT'].fillna(0)


# 3. Previous application status counts
count_cols = [
    'PREV_STATUS_APPROVED',
    'PREV_STATUS_CANCELED',
    'PREV_STATUS_REFUSED',
    'PREV_STATUS_UNUSED_OFFER'
]

df[count_cols] = df[count_cols].fillna(0)


# 4. Historical numerical features
prev_numeric_cols = [
    'PREV_AMT_APPLICATION_MEAN',
    'PREV_AMT_APPLICATION_MAX',
    'PREV_AMT_CREDIT_MEAN',
    'PREV_AMT_CREDIT_MAX',
    'PREV_AMT_ANNUITY_MEAN',
    'PREV_AMT_GOODS_PRICE_MEAN',
    'PREV_CNT_PAYMENT_MEAN',
    'PREV_AMT_DOWN_PAYMENT_MEAN',
    'PREV_RATE_DOWN_PAYMENT_MEAN'
]

df[prev_numeric_cols] = df[prev_numeric_cols].fillna(0)


# 5. Historical rates
rate_cols = [
    'PREV_APPROVAL_RATE',
    'PREV_REFUSAL_RATE'
]

df[rate_cols] = df[rate_cols].fillna(0)

In [45]:
df[
    ['PREV_APP_COUNT'] +
    count_cols +
    prev_numeric_cols +
    rate_cols +
    ['HAS_PREV_APPLICATION']
].isnull().sum()

PREV_APP_COUNT                 0
PREV_STATUS_APPROVED           0
PREV_STATUS_CANCELED           0
PREV_STATUS_REFUSED            0
PREV_STATUS_UNUSED_OFFER       0
PREV_AMT_APPLICATION_MEAN      0
PREV_AMT_APPLICATION_MAX       0
PREV_AMT_CREDIT_MEAN           0
PREV_AMT_CREDIT_MAX            0
PREV_AMT_ANNUITY_MEAN          0
PREV_AMT_GOODS_PRICE_MEAN      0
PREV_CNT_PAYMENT_MEAN          0
PREV_AMT_DOWN_PAYMENT_MEAN     0
PREV_RATE_DOWN_PAYMENT_MEAN    0
PREV_APPROVAL_RATE             0
PREV_REFUSAL_RATE              0
HAS_PREV_APPLICATION           0
dtype: int64

In [46]:
bureau_balance_df = pd.read_csv('../data/raw/bureau_balance.csv')

print(bureau_balance_df.shape)

(27299925, 3)

In [47]:
print(bureau_balance_df.head())

   SK_ID_BUREAU  MONTHS_BALANCE STATUS
0       5715448               0      C
1       5715448              -1      C
2       5715448              -2      C
3       5715448              -3      C
4       5715448              -4      C

In [48]:
print(bureau_balance_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 27299925 entries, 0 to 27299924
Data columns (total 3 columns):
 #   Column          Dtype
---  ------          -----
 0   SK_ID_BUREAU    int64
 1   MONTHS_BALANCE  int64
 2   STATUS          str
dtypes: int64(2), str(1)
memory usage: 650.9 MB
None

In [49]:
bureau_balance_null_percentage = (
    bureau_balance_df.isnull().mean() * 100
).sort_values(ascending=False)

print(
    bureau_balance_null_percentage[
        bureau_balance_null_percentage > 0
    ]
)

Series([], dtype: float64)

In [50]:
print(bureau_balance_df['STATUS'].value_counts())

STATUS
C    13646993
0     7499507
X     5810482
1      242347
5       62406
2       23419
3        8924
4        5847
Name: count, dtype: int64

In [51]:
bureau_balance_fe = (
    bureau_balance_df.groupby('SK_ID_BUREAU')
    .agg(
        BUREAU_BAL_MONTHS_COUNT=('MONTHS_BALANCE', 'count'),
        BUREAU_BAL_MONTHS_MIN=('MONTHS_BALANCE', 'min'),
        BUREAU_BAL_MONTHS_MAX=('MONTHS_BALANCE', 'max')
    )
    .reset_index()
)

In [52]:
print(bureau_balance_fe.head())

   SK_ID_BUREAU  BUREAU_BAL_MONTHS_COUNT  BUREAU_BAL_MONTHS_MIN  \
0       5001709                       97                    -96
1       5001710                       83                    -82
2       5001711                        4                     -3
3       5001712                       19                    -18
4       5001713                       22                    -21

   BUREAU_BAL_MONTHS_MAX
0                      0
1                      0
2                      0
3                      0
4                      0

In [53]:
status_counts = pd.crosstab(
    bureau_balance_df['SK_ID_BUREAU'],
    bureau_balance_df['STATUS']
)

# Remove the index name to avoid ambiguity
status_counts.index.name = None

# Convert SK_ID_BUREAU index into a normal column
status_counts = pd.crosstab(
    bureau_balance_df['SK_ID_BUREAU'],
    bureau_balance_df['STATUS']
).reset_index()

# Rename columns
status_counts = status_counts.rename(
    columns={
        col: f'BUREAU_BAL_STATUS_{col}_COUNT'
        for col in status_counts.columns
        if col != 'SK_ID_BUREAU'
    }
)

In [54]:
print("bureau_balance_fe index name:", bureau_balance_fe.index.name)
print("bureau_balance_fe columns:", bureau_balance_fe.columns.tolist())

print("\nstatus_counts index name:", status_counts.index.name)
print("status_counts columns:", status_counts.columns.tolist())

bureau_balance_fe index name: None
bureau_balance_fe columns: ['SK_ID_BUREAU', 'BUREAU_BAL_MONTHS_COUNT', 'BUREAU_BAL_MONTHS_MIN', 'BUREAU_BAL_MONTHS_MAX']

status_counts index name: None
status_counts columns: ['SK_ID_BUREAU', 'BUREAU_BAL_STATUS_0_COUNT', 'BUREAU_BAL_STATUS_1_COUNT', 'BUREAU_BAL_STATUS_2_COUNT', 'BUREAU_BAL_STATUS_3_COUNT', 'BUREAU_BAL_STATUS_4_COUNT', 'BUREAU_BAL_STATUS_5_COUNT', 'BUREAU_BAL_STATUS_C_COUNT', 'BUREAU_BAL_STATUS_X_COUNT']

In [55]:
bureau_balance_fe = bureau_balance_fe.merge(
    status_counts,
    on='SK_ID_BUREAU',
    how='left'
)

In [56]:
print(bureau_balance_fe.shape)
print(bureau_balance_fe.head())

print(
    "Duplicate SK_ID_BUREAU:",
    bureau_balance_fe['SK_ID_BUREAU'].duplicated().sum()
)

(817395, 12)
   SK_ID_BUREAU  BUREAU_BAL_MONTHS_COUNT  BUREAU_BAL_MONTHS_MIN  \
0       5001709                       97                    -96
1       5001710                       83                    -82
2       5001711                        4                     -3
3       5001712                       19                    -18
4       5001713                       22                    -21

   BUREAU_BAL_MONTHS_MAX  BUREAU_BAL_STATUS_0_COUNT  \
0                      0                          0
1                      0                          5
2                      0                          3
3                      0                         10
4                      0                          0

   BUREAU_BAL_STATUS_1_COUNT  BUREAU_BAL_STATUS_2_COUNT  \
0                          0                          0
1                          0                          0
2                          0                          0
3                          0                          0
4                          0                          0

   BUREAU_BAL_STATUS_3_COUNT  BUREAU_BAL_STATUS_4_COUNT  \
0                          0                          0
1                          0                          0
2                          0                          0
3                          0                          0
4                          0                          0

   BUREAU_BAL_STATUS_5_COUNT  BUREAU_BAL_STATUS_C_COUNT  \
0                          0                         86
1                          0                         48
2                          0                          0
3                          0                          9
4                          0                          0

   BUREAU_BAL_STATUS_X_COUNT
0                         11
1                         30
2                          1
3                          0
4                         22
Duplicate SK_ID_BUREAU: 0

In [57]:
bureau_balance_fe['BUREAU_BAL_DPD_MONTHS'] = (
    bureau_balance_fe['BUREAU_BAL_STATUS_1_COUNT'] +
    bureau_balance_fe['BUREAU_BAL_STATUS_2_COUNT'] +
    bureau_balance_fe['BUREAU_BAL_STATUS_3_COUNT'] +
    bureau_balance_fe['BUREAU_BAL_STATUS_4_COUNT'] +
    bureau_balance_fe['BUREAU_BAL_STATUS_5_COUNT']
)

In [58]:
bureau_balance_fe['BUREAU_BAL_SEVERE_DPD_MONTHS'] = (
    bureau_balance_fe['BUREAU_BAL_STATUS_3_COUNT'] +
    bureau_balance_fe['BUREAU_BAL_STATUS_4_COUNT'] +
    bureau_balance_fe['BUREAU_BAL_STATUS_5_COUNT']
)

In [59]:
bureau_balance_fe['BUREAU_BAL_DPD_RATE'] = (
    bureau_balance_fe['BUREAU_BAL_DPD_MONTHS'] /
    bureau_balance_fe['BUREAU_BAL_MONTHS_COUNT']
)

In [60]:
print(
    bureau_balance_fe[
        [
            'SK_ID_BUREAU',
            'BUREAU_BAL_MONTHS_COUNT',
            'BUREAU_BAL_DPD_MONTHS',
            'BUREAU_BAL_SEVERE_DPD_MONTHS',
            'BUREAU_BAL_DPD_RATE'
        ]
    ].head()
)

   SK_ID_BUREAU  BUREAU_BAL_MONTHS_COUNT  BUREAU_BAL_DPD_MONTHS  \
0       5001709                       97                      0
1       5001710                       83                      0
2       5001711                        4                      0
3       5001712                       19                      0
4       5001713                       22                      0

   BUREAU_BAL_SEVERE_DPD_MONTHS  BUREAU_BAL_DPD_RATE
0                             0                  0.0
1                             0                  0.0
2                             0                  0.0
3                             0                  0.0
4                             0                  0.0

In [61]:
bureau_df = pd.read_csv('../data/raw/bureau.csv')

print(bureau_df.shape)

(1716428, 17)

In [62]:
print(bureau_df.head())

   SK_ID_CURR  SK_ID_BUREAU CREDIT_ACTIVE CREDIT_CURRENCY  DAYS_CREDIT  \
0      215354       5714462        Closed      currency 1         -497
1      215354       5714463        Active      currency 1         -208
2      215354       5714464        Active      currency 1         -203
3      215354       5714465        Active      currency 1         -203
4      215354       5714466        Active      currency 1         -629

   CREDIT_DAY_OVERDUE  DAYS_CREDIT_ENDDATE  DAYS_ENDDATE_FACT  \
0                   0               -153.0             -153.0
1                   0               1075.0                NaN
2                   0                528.0                NaN
3                   0                  NaN                NaN
4                   0               1197.0                NaN

   AMT_CREDIT_MAX_OVERDUE  CNT_CREDIT_PROLONG  AMT_CREDIT_SUM  \
0                     NaN                   0         91323.0
1                     NaN                   0        225000.0
2                     NaN                   0        464323.5
3                     NaN                   0         90000.0
4                 77674.5                   0       2700000.0

   AMT_CREDIT_SUM_DEBT  AMT_CREDIT_SUM_LIMIT  AMT_CREDIT_SUM_OVERDUE  \
0                  0.0                   NaN                     0.0
1             171342.0                   NaN                     0.0
2                  NaN                   NaN                     0.0
3                  NaN                   NaN                     0.0
4                  NaN                   NaN                     0.0

       CREDIT_TYPE  DAYS_CREDIT_UPDATE  AMT_ANNUITY
0  Consumer credit                -131          NaN
1      Credit card                 -20          NaN
2  Consumer credit                 -16          NaN
3      Credit card                 -16          NaN
4  Consumer credit                 -21          NaN

In [63]:
bureau_null_percentage = (
    bureau_df.isnull().mean() * 100
).sort_values(ascending=False)

print(bureau_null_percentage[bureau_null_percentage > 0])

AMT_ANNUITY               71.473490
AMT_CREDIT_MAX_OVERDUE    65.513264
DAYS_ENDDATE_FACT         36.916958
AMT_CREDIT_SUM_LIMIT      34.477415
AMT_CREDIT_SUM_DEBT       15.011932
DAYS_CREDIT_ENDDATE        6.149573
AMT_CREDIT_SUM             0.000757
dtype: float64

In [64]:
print(bureau_df['CREDIT_ACTIVE'].value_counts())
print()
print(bureau_df['CREDIT_TYPE'].value_counts())

CREDIT_ACTIVE
Closed      1079273
Active       630607
Sold           6527
Bad debt         21
Name: count, dtype: int64

CREDIT_TYPE
Consumer credit                                 1251615
Credit card                                      402195
Car loan                                          27690
Mortgage                                          18391
Microloan                                         12413
Loan for business development                      1975
Another type of loan                               1017
Unknown type of loan                                555
Loan for working capital replenishment              469
Cash loan (non-earmarked)                            56
Real estate loan                                     27
Loan for the purchase of equipment                   19
Loan for purchase of shares (margin lending)          4
Mobile operator loan                                  1
Interbank credit                                      1
Name: count, dtype: int64

In [65]:
print(bureau_null_percentage[bureau_null_percentage > 0])

AMT_ANNUITY               71.473490
AMT_CREDIT_MAX_OVERDUE    65.513264
DAYS_ENDDATE_FACT         36.916958
AMT_CREDIT_SUM_LIMIT      34.477415
AMT_CREDIT_SUM_DEBT       15.011932
DAYS_CREDIT_ENDDATE        6.149573
AMT_CREDIT_SUM             0.000757
dtype: float64

In [66]:
bureau_df.groupby('SK_ID_CURR')['AMT_CREDIT_SUM_DEBT'].mean()

SK_ID_CURR
100001     85240.928571
100002     49156.200000
100003         0.000000
100004         0.000000
100005    189469.500000
              ...
456249     16307.100000
456250    744013.365000
456253    448958.250000
456254         0.000000
456255    191864.126250
Name: AMT_CREDIT_SUM_DEBT, Length: 305811, dtype: float64

In [67]:
print(bureau_balance_fe.shape)
print(bureau_balance_fe.columns.tolist())

(817395, 15)
['SK_ID_BUREAU', 'BUREAU_BAL_MONTHS_COUNT', 'BUREAU_BAL_MONTHS_MIN', 'BUREAU_BAL_MONTHS_MAX', 'BUREAU_BAL_STATUS_0_COUNT', 'BUREAU_BAL_STATUS_1_COUNT', 'BUREAU_BAL_STATUS_2_COUNT', 'BUREAU_BAL_STATUS_3_COUNT', 'BUREAU_BAL_STATUS_4_COUNT', 'BUREAU_BAL_STATUS_5_COUNT', 'BUREAU_BAL_STATUS_C_COUNT', 'BUREAU_BAL_STATUS_X_COUNT', 'BUREAU_BAL_DPD_MONTHS', 'BUREAU_BAL_SEVERE_DPD_MONTHS', 'BUREAU_BAL_DPD_RATE']

In [68]:
bureau_enriched = bureau_df.merge(
    bureau_balance_fe,
    on='SK_ID_BUREAU',
    how='left'
)

In [69]:
print("bureau_df shape:", bureau_df.shape)
print("bureau_enriched shape:", bureau_enriched.shape)

print(
    "Duplicate SK_ID_BUREAU:",
    bureau_enriched['SK_ID_BUREAU'].duplicated().sum()
)

bureau_df shape: (1716428, 17)
bureau_enriched shape: (1716428, 31)
Duplicate SK_ID_BUREAU: 0

In [70]:
print(
    bureau_enriched['BUREAU_BAL_MONTHS_COUNT'].isnull().sum()
)

942074

In [71]:
bureau_balance_cols = [
    'BUREAU_BAL_MONTHS_COUNT',
    'BUREAU_BAL_MONTHS_MIN',
    'BUREAU_BAL_MONTHS_MAX',
    'BUREAU_BAL_STATUS_0_COUNT',
    'BUREAU_BAL_STATUS_1_COUNT',
    'BUREAU_BAL_STATUS_2_COUNT',
    'BUREAU_BAL_STATUS_3_COUNT',
    'BUREAU_BAL_STATUS_4_COUNT',
    'BUREAU_BAL_STATUS_5_COUNT',
    'BUREAU_BAL_STATUS_C_COUNT',
    'BUREAU_BAL_STATUS_X_COUNT',
    'BUREAU_BAL_DPD_MONTHS',
    'BUREAU_BAL_SEVERE_DPD_MONTHS',
    'BUREAU_BAL_DPD_RATE'
]

bureau_enriched[bureau_balance_cols] = (
    bureau_enriched[bureau_balance_cols].fillna(0)
)

In [72]:
print(
    bureau_enriched[bureau_balance_cols].isnull().sum()
)

BUREAU_BAL_MONTHS_COUNT         0
BUREAU_BAL_MONTHS_MIN           0
BUREAU_BAL_MONTHS_MAX           0
BUREAU_BAL_STATUS_0_COUNT       0
BUREAU_BAL_STATUS_1_COUNT       0
BUREAU_BAL_STATUS_2_COUNT       0
BUREAU_BAL_STATUS_3_COUNT       0
BUREAU_BAL_STATUS_4_COUNT       0
BUREAU_BAL_STATUS_5_COUNT       0
BUREAU_BAL_STATUS_C_COUNT       0
BUREAU_BAL_STATUS_X_COUNT       0
BUREAU_BAL_DPD_MONTHS           0
BUREAU_BAL_SEVERE_DPD_MONTHS    0
BUREAU_BAL_DPD_RATE             0
dtype: int64

In [73]:
bureau_enriched['AMT_CREDIT_SUM'] = (
    bureau_enriched['AMT_CREDIT_SUM']
    .fillna(bureau_enriched['AMT_CREDIT_SUM'].median())
)

In [74]:
bureau_agg = bureau_enriched.groupby('SK_ID_CURR').agg(
    
    # Number of bureau credit records
    BUREAU_RECORD_COUNT=('SK_ID_BUREAU', 'count'),
    
    # Credit amounts
    BUREAU_CREDIT_SUM_MEAN=('AMT_CREDIT_SUM', 'mean'),
    BUREAU_CREDIT_SUM_MAX=('AMT_CREDIT_SUM', 'max'),
    BUREAU_CREDIT_SUM_SUM=('AMT_CREDIT_SUM', 'sum'),
    
    # Debt
    BUREAU_DEBT_MEAN=('AMT_CREDIT_SUM_DEBT', 'mean'),
    BUREAU_DEBT_MAX=('AMT_CREDIT_SUM_DEBT', 'max'),
    BUREAU_DEBT_SUM=('AMT_CREDIT_SUM_DEBT', 'sum'),
    
    # Credit limit
    BUREAU_CREDIT_LIMIT_MEAN=('AMT_CREDIT_SUM_LIMIT', 'mean'),
    BUREAU_CREDIT_LIMIT_MAX=('AMT_CREDIT_SUM_LIMIT', 'max'),
    
    # Overdue
    BUREAU_OVERDUE_MAX=('AMT_CREDIT_MAX_OVERDUE', 'max'),
    
    # Bureau balance history
    BUREAU_BAL_MONTHS_TOTAL=('BUREAU_BAL_MONTHS_COUNT', 'sum'),
    BUREAU_BAL_DPD_MONTHS_TOTAL=('BUREAU_BAL_DPD_MONTHS', 'sum'),
    BUREAU_BAL_SEVERE_DPD_MONTHS_TOTAL=(
        'BUREAU_BAL_SEVERE_DPD_MONTHS', 'sum'
    ),
    BUREAU_BAL_DPD_RATE_MEAN=('BUREAU_BAL_DPD_RATE', 'mean')
    
).reset_index()

In [75]:
print(bureau_agg.shape)

(305811, 15)

In [76]:
print(bureau_agg.head())

   SK_ID_CURR  BUREAU_RECORD_COUNT  BUREAU_CREDIT_SUM_MEAN  \
0      100001                    7           207623.571429
1      100002                    8           108131.945625
2      100003                    4           254350.125000
3      100004                    2            94518.900000
4      100005                    3           219042.000000

   BUREAU_CREDIT_SUM_MAX  BUREAU_CREDIT_SUM_SUM  BUREAU_DEBT_MEAN  \
0               378000.0            1453365.000      85240.928571
1               450000.0             865055.565      49156.200000
2               810000.0            1017400.500          0.000000
3                94537.8             189037.800          0.000000
4               568800.0             657126.000     189469.500000

   BUREAU_DEBT_MAX  BUREAU_DEBT_SUM  BUREAU_CREDIT_LIMIT_MEAN  \
0         373239.0         596686.5                   0.00000
1         245781.0         245781.0                7997.14125
2              0.0              0.0              202500.00000
3              0.0              0.0                   0.00000
4         543087.0         568408.5                   0.00000

   BUREAU_CREDIT_LIMIT_MAX  BUREAU_OVERDUE_MAX  BUREAU_BAL_MONTHS_TOTAL  \
0                    0.000                 NaN                    172.0
1                31988.565            5043.645                    110.0
2               810000.000               0.000                      0.0
3                    0.000               0.000                      0.0
4                    0.000               0.000                     21.0

   BUREAU_BAL_DPD_MONTHS_TOTAL  BUREAU_BAL_SEVERE_DPD_MONTHS_TOTAL  \
0                          1.0                                 0.0
1                         27.0                                 0.0
2                          0.0                                 0.0
3                          0.0                                 0.0
4                          0.0                                 0.0

   BUREAU_BAL_DPD_RATE_MEAN
0                  0.007519
1                  0.255682
2                  0.000000
3                  0.000000
4                  0.000000

In [77]:
print(bureau_agg.isnull().sum())

SK_ID_CURR                                0
BUREAU_RECORD_COUNT                       0
BUREAU_CREDIT_SUM_MEAN                    0
BUREAU_CREDIT_SUM_MAX                     0
BUREAU_CREDIT_SUM_SUM                     0
BUREAU_DEBT_MEAN                       8372
BUREAU_DEBT_MAX                        8372
BUREAU_DEBT_SUM                           0
BUREAU_CREDIT_LIMIT_MEAN              25308
BUREAU_CREDIT_LIMIT_MAX               25308
BUREAU_OVERDUE_MAX                    92840
BUREAU_BAL_MONTHS_TOTAL                   0
BUREAU_BAL_DPD_MONTHS_TOTAL               0
BUREAU_BAL_SEVERE_DPD_MONTHS_TOTAL        0
BUREAU_BAL_DPD_RATE_MEAN                  0
dtype: int64

In [78]:
bureau_missing_cols = [
    'BUREAU_DEBT_MEAN',
    'BUREAU_DEBT_MAX',
    'BUREAU_CREDIT_LIMIT_MEAN',
    'BUREAU_CREDIT_LIMIT_MAX',
    'BUREAU_OVERDUE_MAX'
]

for col in bureau_missing_cols:
    bureau_agg[f'{col}_MISSING'] = bureau_agg[col].isnull().astype(int)

In [79]:
bureau_agg[bureau_missing_cols] = (
    bureau_agg[bureau_missing_cols].fillna(0)
)

In [80]:
print(bureau_agg.isnull().sum())

SK_ID_CURR                            0
BUREAU_RECORD_COUNT                   0
BUREAU_CREDIT_SUM_MEAN                0
BUREAU_CREDIT_SUM_MAX                 0
BUREAU_CREDIT_SUM_SUM                 0
BUREAU_DEBT_MEAN                      0
BUREAU_DEBT_MAX                       0
BUREAU_DEBT_SUM                       0
BUREAU_CREDIT_LIMIT_MEAN              0
BUREAU_CREDIT_LIMIT_MAX               0
BUREAU_OVERDUE_MAX                    0
BUREAU_BAL_MONTHS_TOTAL               0
BUREAU_BAL_DPD_MONTHS_TOTAL           0
BUREAU_BAL_SEVERE_DPD_MONTHS_TOTAL    0
BUREAU_BAL_DPD_RATE_MEAN              0
BUREAU_DEBT_MEAN_MISSING              0
BUREAU_DEBT_MAX_MISSING               0
BUREAU_CREDIT_LIMIT_MEAN_MISSING      0
BUREAU_CREDIT_LIMIT_MAX_MISSING       0
BUREAU_OVERDUE_MAX_MISSING            0
dtype: int64

In [81]:
print(bureau_agg.shape)
print(bureau_agg['SK_ID_CURR'].duplicated().sum())

(305811, 20)
0

In [82]:
df = df.merge(
    bureau_agg,
    on='SK_ID_CURR',
    how='left'
)

In [83]:
print(df.shape)

(307511, 130)

In [84]:
bureau_features = bureau_agg.columns.drop('SK_ID_CURR')

print(df[bureau_features].isnull().sum())

BUREAU_RECORD_COUNT                   44020
BUREAU_CREDIT_SUM_MEAN                44020
BUREAU_CREDIT_SUM_MAX                 44020
BUREAU_CREDIT_SUM_SUM                 44020
BUREAU_DEBT_MEAN                      44020
BUREAU_DEBT_MAX                       44020
BUREAU_DEBT_SUM                       44020
BUREAU_CREDIT_LIMIT_MEAN              44020
BUREAU_CREDIT_LIMIT_MAX               44020
BUREAU_OVERDUE_MAX                    44020
BUREAU_BAL_MONTHS_TOTAL               44020
BUREAU_BAL_DPD_MONTHS_TOTAL           44020
BUREAU_BAL_SEVERE_DPD_MONTHS_TOTAL    44020
BUREAU_BAL_DPD_RATE_MEAN              44020
BUREAU_DEBT_MEAN_MISSING              44020
BUREAU_DEBT_MAX_MISSING               44020
BUREAU_CREDIT_LIMIT_MEAN_MISSING      44020
BUREAU_CREDIT_LIMIT_MAX_MISSING       44020
BUREAU_OVERDUE_MAX_MISSING            44020
dtype: int64

In [85]:
df[bureau_features] = df[bureau_features].fillna(0)

In [86]:
print(df[bureau_features].isnull().sum())

BUREAU_RECORD_COUNT                   0
BUREAU_CREDIT_SUM_MEAN                0
BUREAU_CREDIT_SUM_MAX                 0
BUREAU_CREDIT_SUM_SUM                 0
BUREAU_DEBT_MEAN                      0
BUREAU_DEBT_MAX                       0
BUREAU_DEBT_SUM                       0
BUREAU_CREDIT_LIMIT_MEAN              0
BUREAU_CREDIT_LIMIT_MAX               0
BUREAU_OVERDUE_MAX                    0
BUREAU_BAL_MONTHS_TOTAL               0
BUREAU_BAL_DPD_MONTHS_TOTAL           0
BUREAU_BAL_SEVERE_DPD_MONTHS_TOTAL    0
BUREAU_BAL_DPD_RATE_MEAN              0
BUREAU_DEBT_MEAN_MISSING              0
BUREAU_DEBT_MAX_MISSING               0
BUREAU_CREDIT_LIMIT_MEAN_MISSING      0
BUREAU_CREDIT_LIMIT_MAX_MISSING       0
BUREAU_OVERDUE_MAX_MISSING            0
dtype: int64

In [87]:
pos_cash_df = pd.read_csv('../data/raw/POS_CASH_balance.csv')

In [88]:
print(pos_cash_df.shape)

(10001358, 8)

In [89]:
print(pos_cash_df.head())

   SK_ID_PREV  SK_ID_CURR  MONTHS_BALANCE  CNT_INSTALMENT  \
0     1803195      182943             -31            48.0
1     1715348      367990             -33            36.0
2     1784872      397406             -32            12.0
3     1903291      269225             -35            48.0
4     2341044      334279             -35            36.0

   CNT_INSTALMENT_FUTURE NAME_CONTRACT_STATUS  SK_DPD  SK_DPD_DEF
0                   45.0               Active       0           0
1                   35.0               Active       0           0
2                    9.0               Active       0           0
3                   42.0               Active       0           0
4                   35.0               Active       0           0

In [90]:
print(pos_cash_df.head())

   SK_ID_PREV  SK_ID_CURR  MONTHS_BALANCE  CNT_INSTALMENT  \
0     1803195      182943             -31            48.0
1     1715348      367990             -33            36.0
2     1784872      397406             -32            12.0
3     1903291      269225             -35            48.0
4     2341044      334279             -35            36.0

   CNT_INSTALMENT_FUTURE NAME_CONTRACT_STATUS  SK_DPD  SK_DPD_DEF
0                   45.0               Active       0           0
1                   35.0               Active       0           0
2                    9.0               Active       0           0
3                   42.0               Active       0           0
4                   35.0               Active       0           0

In [91]:
print(pos_cash_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10001358 entries, 0 to 10001357
Data columns (total 8 columns):
 #   Column                 Dtype
---  ------                 -----
 0   SK_ID_PREV             int64
 1   SK_ID_CURR             int64
 2   MONTHS_BALANCE         int64
 3   CNT_INSTALMENT         float64
 4   CNT_INSTALMENT_FUTURE  float64
 5   NAME_CONTRACT_STATUS   str
 6   SK_DPD                 int64
 7   SK_DPD_DEF             int64
dtypes: float64(2), int64(5), str(1)
memory usage: 669.9 MB
None

In [92]:
print(pos_cash_df.columns.tolist())

['SK_ID_PREV', 'SK_ID_CURR', 'MONTHS_BALANCE', 'CNT_INSTALMENT', 'CNT_INSTALMENT_FUTURE', 'NAME_CONTRACT_STATUS', 'SK_DPD', 'SK_DPD_DEF']

In [93]:
pos_null_percentage = (
    pos_cash_df.isnull().mean() * 100
).sort_values(ascending=False)

In [94]:
print(pos_null_percentage[pos_null_percentage > 0])

CNT_INSTALMENT_FUTURE    0.260835
CNT_INSTALMENT           0.260675
dtype: float64